### PR TITLE
Added CNAME

### PR DESCRIPTION
**Pull request by ogenstad**

### CODE REVIEW

**Comment by mirceaulinic** [comment]
> Fastly error: unknown domain: www.netsysops.io. Please check that this domain has been added to a service.

:(

**Comment by ogenstad** [comment]
Yeah it's a work in progress. @dbarrosop is hunting someone.

**Comment by mirceaulinic** [comment]
Okay..I thought these things are almost instantly updated. Unless they're done manually :D

**Comment by ogenstad** [comment]
:) It should be pretty instant, however nothing is setup on the Fastly side yet. :) The CNAME was just to prepare for that.

**Comment by mirceaulinic** [comment]
Hmm.. feels a bit Slow(ly) :D

**Comment by ogenstad** [comment]
[Censored removed] :)

**Pull request merged**
